name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 4.8
        platform: x86
        
    - uses: actions/checkout@v2
    - name: make
      run: makeall.bat
